#!/bin/sh

PROVIDER=${1:-internal}
GPIODIR=/sys/class/gpio/gpio175

if [ ! -d "$GPIODIR" ]
then
        echo 175 > /sys/class/gpio/export
fi

echo out > ${GPIODIR}/direction

if [ "${PROVIDER}" = "internal" ]
then
        echo selecting internal sim
        echo 1 > ${GPIODIR}/value
else
        echo selecting external sim
        echo 0 > ${GPIODIR}/value
fi

if [ "$1" = "quick" ]
then
    touch /var/run/ppp-quick
    shift
fi

/usr/sbin/pppd call ${PROVIDER}
